dpi-aware=yes
icon-theme=Papirus-Dark
width=20
font=Hack:weight=bold:size=11
line-height=24
fields=name,generic,comment,categories,filename,keywords
terminal=alacritty -e
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=no

include=./catppuccin-macchiato/lavender.ini
; [colors]
; background=282a36fa
; selection=3d4474fa
; border=fffffffa

[border]
radius=20

[dmenu]
exit-immediately-if-empty=yes
