general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"

[font]
size = 11.0

[font.normal]
family = "CaskaydiaCove Nerd Font"

[font.bold]
family = "CaskaydiaCove Nerd Font"

[font.italic]
family = "CaskaydiaCove Nerd Font"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"

[scrolling]
history = 10000
multiplier = 3
